### ISSUE TITLE
Typo in Scheme Section: Zero-padded year example

### ISSUE THREAD

**Issue by vidit-maheshwari** [mahmoud/calver#55]
# Typo in CalVer Scheme Section

In the "Scheme" section of the CalVer website (https://calver.org/#scheme), there's a typo in the description of the "0Y" format specifier.

Currently, it reads: "0Y - Zero-padded year - 06, 16, 106".

However, the example "106" is inconsistent with the intended format and might cause confusion for users. It should be corrected to "16" to align with the expected output of zero-padding the year.

**Comment by mahmoud** [comment]
Hey Vidit! So, you'll note that `16` is actually already in the list, and the 106 is intentional:

>  0Y - Zero-padded year - 06, 16, 106

The original purpose of 106 here is to show that even when I'm long gone and 2106 rolls around, a user of the **0Y** format would roll over to three digits as well. Zero padding with **0Y** implies one zero's worth of padding for a truncated year.

On further thought, a better description should explain that CalVer versions must be monotonically incrementing, and especially never revert to version 0. So a CalVer user at version 99 should go to 100. But arguably CalVer user just starting in 2106 can feel free to start at 6 (YY) or 06 (0Y). 

Practically, since we're on the topic of far-future mechanics: in 75 years (and every century marker) I predict we'll have a big conversion of truncated year versions (0Y and YY) to full year versions (YYYY) to avoid confusion.

Does that make sense? I'm not super inclined to add a lot of text about this corner case, since I doubt I'll be maintaining CalVer when it becomes relevant, but I'm open to PRs :)

**Comment by vidit-maheshwari** [comment]
Got it thanks
